name: Build and Deploy to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t rcvregistry-hrdvere2a3d7e4dh.azurecr.io/smiles_api:${{ github.sha }} .

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push rcvregistry-hrdvere2a3d7e4dh.azurecr.io/smiles_api:${{ github.sha }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-container-action@v1
        with:
          app-name: "smiles-api"
          image: "mrcvregistry-hrdvere2a3d7e4dh.azurecr.io/smiles_api:${{ github.sha }}"
          resource-group: "anima-rg-435"
